exercises/ex_authentication/config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  get "products/new"
  get "products/create"
  get "products/edit"
  get "products/update"
  get "products/destroy"
  get "xyz/index"
  get "xyz/new"
  get "xyz/create"
  get "xyz/edit"
  get "xyz/update"
  get "xyz/destroy"
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "customers/edit_customer", to: "customers#edit_customer", as: "edit_customer"
  post "customers/manage_customer", to: "customers#manage_customer", as: "manage_customer"


  get "roles/:id/permissions", to: "roles#permissions", as: "permissions"
  post "roles/:id/store_permissions", to: "roles#store_permissions", as: "store_permissions"

  get "dashboard/lock_accounts", to: "dashboard#lock_accounts", as: "lock_accounts"
  get "dashboard/:id/unlock_accounts", to: "dashboard#unlock_accounts", as: "unlock_accounts"


  resources :roles
  resources :staff_users
  resources :customers, only: [ :edit, :update ]
  resources :dashboard, only: [ :index ]
  resources :products
  root "dashboard#index"
end

exercises/ex_authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ex Authentication" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
  </head>

  <body>

    <% flash.each do |key, value| %>
      	<div class="alert alert-<%= key %> alert-dismissible flash-message" role="alert">
        	<%= value %>
      	</div>
    <% end %>

  <nav class="navbar navbar-light bg-dark justify-content-between">
    <h5 class="navbar-brand margin-left text-primary">Authentication Demo<br />
     	<%= link_to 'Home', root_path %>
   	</h5>
    <% if admin_signed_in? %>
     	<a class="navbar-brand margin-left text-primary">Welcome <%= current_admin.username %></a>
        

   	<% end %>


    <form class="form-inline">
 	<% if admin_signed_in? %> 
      		<%= link_to "Sign out", destroy_admin_session_path, data: { turbo_method: :delete }, class: "btn btn-outline-success my-2 margin-right my-sm-0" %>
 	<% else %>
      		<%= link_to "Sign in", new_admin_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      		<%= link_to "Sign Up", new_admin_registration_path, class: "btn btn-outline-success my-2 my-sm-0 margin-right" %>
 	<% end %>
    </form>

	</nav>
    <%= yield %>
  </body>
</html>