solutions/cruddemowithjoins/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "employees" => "employees#index", as: "employees"
  get "employees/new" => "employees#new", as: "employee_new"
  get "employees/edit/:id" => "employees#edit", as: "edit_employee"
  get "employees/:id" => "employees#show", as: "employee"
  get "delete_employee/:id" => "employees#delete_employee", as: "delete_employee"


  patch "employees/:id" => "employees#update"
  delete "employees/:id" => "employees#destroy"
  post "employees" => "employees#create", as: "employee_create"

  resources :singleemployeedelete, only: [:index] do
    delete 'emp_delete', on: :collection
    end

    resources :bulkdeleteemployees, only: [:index] do
      delete 'bulk_delete', on: :collection
      end

  resources :bulkupdates, only: [:index] do
    patch 'bulk_update', on: :collection
  end

  resources :bulkinserts, only: [:new, :create]

  resources :offshoreemployees, only: [:new, :create]

  get '/locations/states', to: 'locations#states'
  get '/locations/cities', to: 'locations#cities'

  resources :employeespaginations, only: [:index]

  get 'radio_index', to: "allowances#radio_index"
  post 'radio_create', to: "allowances#radio_create"

  get 'check_box_index', to: "allowances#check_box_index"
  post 'check_box_create', to: "allowances#check_box_create"

  get 'list_box_index', to: "allowances#list_box_index"
  post 'list_box_create', to: "allowances#list_box_create"

  resources :employeefilters, only: [:index]
end

solutions/cruddemowithjoins/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :country
  belongs_to :department

  after_initialize :do_after_initialize

  after_find :output_after_find

  before_save :print_save_message
  around_save :print_around_save_message #it can wrap both before and after save logic
  after_save :print_saved_message

  before_create :print_create_message
  around_create :print_around_create_message
  after_create :print_created_message

  before_update :print_update_message
  around_update :print_around_update_message
  after_update :print_updated_message

  before_destroy :print_destroy_message
  around_destroy :print_around_destroy_message
  after_destroy :print_destroyed_message


  private
  def do_after_initialize
    puts "AFTER INITIALIZE :- Employee initialized with firstname: #{firstname}, lastname: #{lastname}"
  end

  def output_after_find
    puts "AFTER FIND :- Employee found with firstname: #{firstname}, lastname: #{lastname}"
  end

  def print_save_message
    puts 'BEFORE SAVE :- Employee is being saved...'
    today = Date.today
    if today.saturday? || today.sunday?
      errors.add(:base, "Cannot insert record on a Saturday or Sunday")
      throw(:abort)
    end
  end

  def print_around_save_message
    puts 'AROUND SAVE :- Do something before saving'
    yield #employee is now saved
    puts 'AROUND SAVE :- Employee saved successfully!'
  end

  def print_saved_message
    puts 'AFTER SAVE :- Employee saved!'
  end

def print_create_message
  puts 'BEFORE CREATE :- Creating Employee...'
end

def print_around_create_message
  puts 'AROUND CREATE :- Creating around Employee...'
  yield
  puts 'AROUND CREATE :- Employee created!'
end

def print_created_message
  puts 'AFTER CREATE :- Employee created!!'
end

def print_update_message
  puts 'BEFORE UPDATE :- Updating Employee...'
end

def print_around_update_message
  puts 'AROUND UPDATE :- Updating around Employee...'
  yield
  puts 'AROUND UPDATE :- Employee updated!'
end

def print_updated_message
  puts 'AFTER UPDATE :- Employee updated!!'
end

def print_destroy_message
  puts 'BEFORE DESTROY :- Destroying Employee...'
end

def print_around_destroy_message
  puts 'AROUND DESTROY :- Destroying around Employee...'
  yield
  puts 'AROUND DESTROY :- Employee destroyed!'
end

def print_destroyed_message
  puts 'AFTER DESTROY :- Employee destroyed!!'
    Backupemployee.create(firstname: self.firstname, lastname: self.lastname)
  end

















  has_rich_text :notes

  attr_accessor :editable

    #It's a way to name a custom database query, composed of ActiveRecord methods.
    scope :search, ->(query) {

    if query.present?
      left_joins(:department)
        .where("employees.id LIKE ? OR firstname LIKE ? OR lastname LIKE ? OR departments.name LIKE ?",
        "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
    else
      all
    end


  }

end

solutions/cruddemowithjoins/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController


  def index
    @employees=Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

def update
    @employee = Employee.find(params[:id])

      if @employee.update(employee_params)
        redirect_to employees_path()
      else
        render :edit, status: :unprocessable_entity
      end
end

def employee_params
  params.require(:employee).permit(:firstname, :lastname, :haspassport, :salary, :gender, :email, :phone, :birthdate, :hiredate, :notes,:department_id, :country_id)
end

def delete_employee
  @employee = Employee.find(params[:id])
end

def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy!
  redirect_to employees_path
end


def new
  @employee = Employee.new
end

def create
  @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

end

solutions/cruddemowithjoins/app/views/employees/delete_employee.html.erb
<div>
  <h1>Deleting Employee!</h1>
  <h3>Are you sure you want to delete this?</h3>
  <br/>



<%= form_for @employee, html: {class: "form-horizontal",multipart: true} do |f| %>

<fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        First Name: 
      </label>
      <div class="col-sm-10">
        <%= f.text_field :firstname, placeholder: 'Enter First Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Last Name:    
      </label>
      <div class="col-sm-10">
        <%= f.text_field :lastname, placeholder: 'Enter Last Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Has Passport:
      </label>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.check_box :haspassport, { class: 'form-check-input' } %>          
        </div>
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Salary:
      </label>
      <div class="col-sm-10">
        <%= f.text_field :salary, placeholder: 'Enter Salary', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Birth Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :birthdate, class: 'form-control' %>      
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Hiring Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :hiredate, class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

<fieldset>
    <div class="form-group row >
      <legend class="col-form-label col-sm-2 pt-0">Gender:</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.radio_button :gender, 'Male', checked: true, data: { toggle: 'radio' }, class: 'form-check-input', id: 'male' %>
          <label class="form-check-label" for="male">
            Male
          </label>  
        </div>
        <div class="form-check">
          <%= f.radio_button :gender, 'Female', data: { toggle: 'radio' }, class: 'form-check-input', id: 'female' %>
          <label class="form-check-label" for="female">
            Female
          </label>     
        </div>
      </div>
    </div>
  </fieldset>

 <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Notes:
      </label>
      <div class="col-sm-10">
        <%= f.text_area :notes, placeholder: 'Enter Notes', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

  
  

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Email:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.email_field :email, autofocus: true, placeholder: 'Enter Email', class: 'form-control'  %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Phone Number:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.text_field :phone, autofocus: true, placeholder: 'Enter Phone Number', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

<fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Department:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :department_id, options_from_collection_for_select(select_department, 'id', 'name', f.object.department_id), { include_blank: "Select Department"}, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Country:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :country_id, options_from_collection_for_select(select_country, 'id', 'name', f.object.country_id), { include_blank: 'Select Country' }, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>

  
<%= f.submit 'Delete Record', class: "btn btn-primary" %>
<a href="<%= employee_path(@employee) %>" class="btn btn-danger" data-turbo-method="delete" data-turbo-confirm="Are you sure?">Delete</a> |
 <a href="<%= employees_path %>">Back To List</a>
<% end %>

</div>

solutions/cruddemowithjoins/app/views/employees/edit.html.erb
<div>
  <h1>Editing Employee</h1>
  <br/>



<%= form_for @employee, html: {class: "form-horizontal",multipart: true} do |f| %>

<fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        First Name: 
      </label>
      <div class="col-sm-10">
        <%= f.text_field :firstname, placeholder: 'Enter First Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Last Name:    
      </label>
      <div class="col-sm-10">
        <%= f.text_field :lastname, placeholder: 'Enter Last Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Has Passport:
      </label>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.check_box :haspassport, { class: 'form-check-input' } %>          
        </div>
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Salary:
      </label>
      <div class="col-sm-10">
        <%= f.text_field :salary, placeholder: 'Enter Salary', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Birth Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :birthdate, class: 'form-control' %>      
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Hiring Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :hiredate, class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

<fieldset>
    <div class="form-group row >
      <legend class="col-form-label col-sm-2 pt-0">Gender:</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.radio_button :gender, 'Male', checked: true, data: { toggle: 'radio' }, class: 'form-check-input', id: 'male' %>
          <label class="form-check-label" for="male">
            Male
          </label>  
        </div>
        <div class="form-check">
          <%= f.radio_button :gender, 'Female', data: { toggle: 'radio' }, class: 'form-check-input', id: 'female' %>
          <label class="form-check-label" for="female">
            Female
          </label>     
        </div>
      </div>
    </div>
  </fieldset>

 <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Notes:
      </label>
      <div class="col-sm-10">
        <%= f.rich_text_area :notes, placeholder: 'Enter Notes', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

  
  

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Email:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.email_field :email, autofocus: true, placeholder: 'Enter Email', class: 'form-control'  %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Phone Number:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.text_field :phone, autofocus: true, placeholder: 'Enter Phone Number', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Department:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :department_id, options_from_collection_for_select(select_department, 'id', 'name', f.object.department_id), { include_blank: "Select Department"}, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Country:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :country_id, options_from_collection_for_select(select_country, 'id', 'name', f.object.country_id), { include_blank: 'Select Country' }, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>

<%= f.submit 'Update Record', class: "btn btn-primary" %>
 <a href="<%= employees_path %>">Back To List</a>
<% end %>

</div>

solutions/cruddemowithjoins/app/views/employees/index.html.erb
<div>
  <h1>Listing Employees</h1>
  <br/>

<br/><br/>

<a href="<%= employee_new_path %>">New Employee</a>

<% if @employees.present? %>
<table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Department Name</th>
          <th>Country Name</th>
          <th>Actions</th>
        </tr>
      </thead>
 <tbody>
     <% @employees.each do |employee| %>
         <tr>
            <td><%= employee.id %></td>
            <td><%= employee.firstname %></td>
            <td><%= employee.lastname %></td>
            <td><%= employee.phone %></td>
            <td><%= employee.email %></td>    
            <td><%= employee.department.name %></td>
            <td><%= employee.country.name %></td>
            <td> 
                <a href="<%= employee_path(employee) %>">Details</a> |  
                <a href="<%= edit_employee_path(employee) %>">Edit</a> |
                <a href="<%= delete_employee_path(employee) %>">Delete</a>
            
            </td>       
          </tr>
     <% end %>
</tbody>
</table>
 <% end %>
</div>

solutions/cruddemowithjoins/app/views/employees/new.html.erb
<div>
  <h1>Inserting New Employee</h1>
  <br/>



<%= form_for @employee, html: {class: "form-horizontal",multipart: true} do |f| %>

<fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        First Name: 
      </label>
      <div class="col-sm-10">
        <%= f.text_field :firstname, placeholder: 'Enter First Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Last Name:    
      </label>
      <div class="col-sm-10">
        <%= f.text_field :lastname, placeholder: 'Enter Last Name', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Has Passport:
      </label>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.check_box :haspassport, { class: 'form-check-input' } %>          
        </div>
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Salary:
      </label>
      <div class="col-sm-10">
        <%= f.text_field :salary, placeholder: 'Enter Salary', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Birth Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :birthdate, class: 'form-control' %>      
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Hiring Date:
      </label>
      <div class="col-sm-10">
        <%= f.date_field :hiredate, class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

<fieldset>
    <div class="form-group row >
      <legend class="col-form-label col-sm-2 pt-0">Gender:</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <%= f.radio_button :gender, 'Male', checked: true, data: { toggle: 'radio' }, class: 'form-check-input', id: 'male' %>
          <label class="form-check-label" for="male">
            Male
          </label>  
        </div>
        <div class="form-check">
          <%= f.radio_button :gender, 'Female', data: { toggle: 'radio' }, class: 'form-check-input', id: 'female' %>
          <label class="form-check-label" for="female">
            Female
          </label>     
        </div>
      </div>
    </div>
  </fieldset>

 <fieldset>
    <div class="form-group row">
      <label class="col-sm-2 control-label">
        Notes:
      </label>
      <div class="col-sm-10">
        <%= f.rich_text_area :notes, placeholder: 'Enter Notes', class: 'form-control' %>    
      </div>
    </div>
  </fieldset>

  
  

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Email:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.email_field :email, autofocus: true, placeholder: 'Enter Email', class: 'form-control'  %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Phone Number:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.text_field :phone, autofocus: true, placeholder: 'Enter Phone Number', class: 'form-control' %>        
      </div>
    </div>
  </fieldset>

   <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Department:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :department_id, options_from_collection_for_select(select_department, 'id', 'name', f.object.department_id), { include_blank: "Select Department"}, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group row ">
      <label class="col-sm-2 control-label">
        Country:
        <span class="star">*</span>
      </label>
      <div class="col-sm-10">
        <%= f.select :country_id, options_from_collection_for_select(select_country, 'id', 'name', f.object.country_id), { include_blank: 'Select Country' }, class: 'form-control', autofocus: true %>    
      </div>
    </div>
  </fieldset>





<%= f.submit 'Insert Record', class: "btn btn-primary" %>
 <a href="<%= employees_path %>">Back To List</a>
<% end %>

</div>

solutions/cruddemowithjoins/app/views/employees/show.html.erb
<div>
  <h1>Employee Details</h1>
  <br/>


<table class="table">
  <tbody>
    <tr>
      <td>Employee ID</td>
      <td>
        <%= @employee.id %>
      </td>
    </tr>
    <tr>
      <td>First Name</td>
      <td>
        <%= @employee.firstname %>
      </td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td>
        <%= @employee.lastname %>
      </td>
    </tr>
    <tr>
      <td>Has Passport</td>
      <td>
        <%= @employee.haspassport %>
      </td>
    </tr>
    <tr>
      <td>Gender</td>
      <td>
        <%= @employee.gender %>
      </td>
    </tr>
    <tr>
      <td>Salary</td>
      <td>
        <%= @employee.salary %>
      </td>
    </tr>
    <tr>
      <td>Birth Date</td>
      <td>
        <%= @employee.birthdate %>
      </td>
    </tr>
    <tr>
      <td>Hiring Date</td>
      <td>
        <%= @employee.hiredate %>
      </td>
    </tr>            
    <tr>
      <td>Email</td>
      <td>
        <%= @employee.email %>
      </td>
    </tr>
    <tr>
      <td>Phone Number</td>
      <td>
        <%= @employee.phone %>
      </td>
    </tr>
 <tr>
      <td>Notes</td>
      <td>
        <%= @employee.notes %>
      </td>
    </tr>

      <tr>
      <td>Country</td>
      <td>
        <%= @employee.country.name %>
      </td>
    </tr>
    <tr>
      <td>Department</td>
      <td>
        <%= @employee.department.name %>
      </td>
    </tr>
    
  </tbody>
</table>

<a href="<%= employees_path %>">Back To List</a>
</div>