exercises/ex_uploaddownloadfiles/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :employeeinfodetails, only: [ :index, :show, :new, :create ]
  root to: "employeeinfodetails#index"

  get "employees/download_file" => "employeeinfodetails#download_file"
end

exercises/ex_uploaddownloadfiles/app/models/employeecertificate.rb
class Employeecertificate < ApplicationRecord
  belongs_to :employeeinfo
  has_one_attached :certi
end

exercises/ex_uploaddownloadfiles/app/models/employeeinfo.rb
class Employeeinfo < ApplicationRecord
  has_many :employeecertificates, dependent: :destroy
  accepts_nested_attributes_for :employeecertificates
  has_one_attached :pan_card
end

exercises/ex_uploaddownloadfiles/app/controllers/employeeinfodetails_controller.rb
class EmployeeinfodetailsController < ApplicationController
  def index
    @employees = Employeeinfo.all
  end

  def new
    @employee = Employeeinfo.new
  end

  def create
    @employee = Employeeinfo.new(employee_params)
    if @employee.save
      folder_name = "#{@employee.id}_#{@employee.lastname}"
      folder_path = Rails.public_path.join("employee_files", folder_name)
      FileUtils.mkdir_p(folder_path) unless File.directory?(folder_path)

      upload_file(params[:cv], folder_path, "#{folder_name}_cv")
      upload_file(params[:photo], folder_path, "#{folder_name}_my_pic")

      certificate_path = Rails.public_path.join("employee_files", folder_name, "certificates")
      FileUtils.mkdir_p(certificate_path) unless File.directory?(certificate_path)

      params[:employee][:employeecertificates_attributes].each_with_index do |certificate, index|
        upload_file(certificate[:certi], certificate_path, "certificate_#{index+1}")
      end

      @employee.update(certificate_params)
      redirect_to employeeinfodetails_path

    end
  end

  def show
    @employee = Employeeinfo.find_by id: params[:id]

    if @employee.present?
      @folder_name = "#{@employee.id}_#{@employee.lastname}"
      folder_path = Rails.public_path.join("employee_files", @folder_name)
      file_list = Dir["#{folder_path}/*"]

      cv_file_name = file_list.find { |file| file.include?("cv") }.split("/").last
      my_pic_file_name = file_list.find { |file| file.include?("my_pic") }.split("/").last
      @cv_file_path = "employee_files/#{@folder_name}/#{cv_file_name}"
      @my_pic_file_path = "employee_files/#{@folder_name}/#{my_pic_file_name}"

      certi_folder_path = Rails.public_path.join("employee_files", @folder_name, "certificates")
      certi_files = Dir["#{certi_folder_path}/*"]
      @certificates = certi_files.map { |certi| certi[certi.index("employee_files")..(certi.length)] }

    end
  end


  def download_file
    send_file("#{Rails.root}/public/#{params[:download_path]}")
  end


  private
  def employee_params
    params.require(:employeeinfo).permit(:firstname, :lastname, :pan_card)
  end

  def certificate_params
    params.require(:employee).permit(employeecertificates_attributes: [ :certi ])
  end

  def upload_file(uploaded_file, folder_path, new_fname)
    file_name = uploaded_file.original_filename
    file_extension = file_name.split(".").last
    new_file_name = "#{new_fname}.#{file_extension}"

    File.open(File.join(folder_path, new_file_name), "wb") do |file|
      file.write(uploaded_file.read)
    end
  end
end

exercises/ex_uploaddownloadfiles/app/helpers/employeeinfodetails_helper.rb
module EmployeeinfodetailsHelper
end

exercises/ex_uploaddownloadfiles/app/views/employeeinfodetails/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<div class="text-center mt-4 mb-4">
				<h1>Add Files | Employee Information | Yoshi Cooremans</h1>
			</div>
			<%= link_to 'Create', new_employeeinfodetail_path, class: "btn btn-primary mt-4 mb-1" %>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">ID</th>
						<th scope="col">First Name</th>
						<th scope="col">Last Name</th>
						<th scope="col">Actions/Operations</th>
			    	</tr>
			  	</thead>
			  	<tbody>
			  		<% @employees.each do |emp| %>
				    	<tr>
							<th scope="row"><%= emp.id %></th>
							<td><%= emp.firstname %></td>
							<td><%= emp.lastname %></td>
							<td><%= link_to 'Details', employeeinfodetail_path(emp) %></td>
				    	</tr>
				    <% end %>
				    <% unless @employees.present? %>
				    	<tr>
				    		<td colspan="4" class="text-center">No Data Found</td>
				    	</tr>
				    <% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

exercises/ex_uploaddownloadfiles/app/views/employeeinfodetails/new.html.erb
<h1>New File | Employee Information | Yoshi Cooremans</h1>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-4">
            <%= form_for @employee, url: employeeinfodetails_path(@employee), method: :post do |f| %>
                <div class="mb-2">
                    <span>First name: </span>
                    <%= f.text_field :firstname, required: true %>
                </div>
                  <div class="mb-2">
                    <span>Last name: </span>
                    <%= f.text_field :lastname, required: true %>
                </div>

                <div class="mb-2">
                    <span>Cv file: </span>
                    <%= file_field_tag :cv, required: true %>
                </div>

                <div class="mb-2">
                    <span>Photo file: </span>
                    <%= file_field_tag :photo, required: true %>
                </div>

                <div class="mb-4">
                    <span>Pan card pic blob: </span>
                    <%= f.file_field :pan_card, required: true %>
                </div>

                <div class="mb-2">
                    <h5>Certificates</h5>
                </div>
                <div class="mb-2">
                    <%= link_to 'Add Certificates', 'javascript:void(0)', 
                    class: 'btn btn-primary add-certicate' %>
                </div>
                <div class="certificate_list">
                </div>
                 <div class="mb-2">
                    <%= f.submit :Submit, class: 'btn btn-success submit-emp-form' %>
                </div>
                <div class="mb-2">
                    <%= link_to 'Back', employeeinfodetails_path, class: 'btn btn-secondary' %>
                </div>

            <% end %>


        </div>
    </div>
</div>


<div class="certificate_fields d-none">
    <div class="certi-box mb-2">
        <div class="row">
            <div class="col-8">
    <%= file_field_tag "employee[employeecertificates_attributes][][certi]", 
    class: "form-control certificate-file" %>
            </div>
            <div class="col-4">
                <%= link_to "javascript:void(0)", 
                class: 'btn btn-danger remove_certi' do %>
                    <i class="bi bi-trash"></i>
                <% end %>
            </div>
        </div>
    </div>
</div>

exercises/ex_uploaddownloadfiles/app/views/employeeinfodetails/show.html.erb
<h1>Employee Information | Yoshi Cooremans</h1>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-4">
        	<h4 class="mt-2">
        		<%= "#{@employee.firstname} #{@employee.lastname}" %>
        	</h4>
        	<div class="mb-1">
        		<span>CV</span>
        		<%= link_to @cv_file_path, employees_download_file_path(download_path: @cv_file_path) %>
        	</div>

        	<div class="mb-1">
        		<span>Photo</span>
        		<%= link_to @my_pic_file_path, employees_download_file_path(download_path: @my_pic_file_path) %>
        	</div>

        	<div>
        		<div>Pan Card</div>
        		<div>
        			<%= image_tag @employee.pan_card, style: "height: 200px; width: 300px" %>
        		</div>
        	</div>

        	<div>
        		<div>Certificates</div>
        		<ul>
        			<% @certificates.each do |certi| %>
        				<li><%= link_to certi, employees_download_file_path(download_path: certi) %></li>
        			<% end %>
        		</ul>
        	</div>

        	<div class="mt-2">
                <%= link_to 'Back', employeeinfodetails_path, class: 'btn btn-secondary' %>
        	</div>
        </div>
    </div>
</div>