exercises/ex_basicsofrails/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get "home/index" => "home#index"
  get "home/getquerystringvalues" => "home#getQueryStringValues"
  get "home/passdatatoviews" => "home#passDataToViews"
  get "home/showdatetimeinfo" => "home#showDateTimeInfo"
  get "home/conditionalrendering" => "home#conditionalRendering"
  get "home/loopingthrougharray" => "home#loopThroughArrays"

  get "home/loadusers" => "home#LoadUsers"
  get "home/loadusers2" => "home#LoadUsers2"

  get "home/loaduserdetails/:id" => "home#LoadUsersDetails", as: :LoadUserDetails
  get "home/showuserdetails" => "home#ShowUserDetails"

  get "shoppingcart/index" => "shoppingcart#index"
  get "/shoppingcart/product_list" => "shoppingcart#product_list"
  get "/shoppingcart/:product_id/add_cart" => "shoppingcart#add_cart", as: :add_cart
  get "/shoppingcart/:cart_id/remove_cart" => "shoppingcart#remove_cart", as: :remove_cart
end

exercises/ex_basicsofrails/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        # render plain: "Hello World From Rails 8, Yoshi Cooremans!"

        # render html: "<h1>Hello World From Rails 8, Yoshi Cooremans!</h1>".html_safe

        message = "<h1>Hello World From Rails 8, Yoshi Cooremans!</h1>"
        message += "<h2>Hello World From Rails 8, Yoshi Cooremans!</h2>"
        message += "<h3>Hello World From Rails 8, Yoshi Cooremans!</h3>"
        message += "<h4>Hello World From Rails 8, Yoshi Cooremans!</h4>"
        message += "<h5>Hello World From Rails 8, Yoshi Cooremans!</h5>"
        message += "<h6>Hello World From Rails 8, Yoshi Cooremans!</h6>"

        render html: message.html_safe
    end

    def getQueryStringValues
        message = ""

        if params[:message]
            message += "<h1>Message is: #{params[:message]}</h1>"
        else
                message += "<h1>No message received</h1>"
        end

        if params[:country]
            message += "<h1>Country is: #{params[:country]}</h1>"
        else
            message += "<h1>No country received</h1>"
        end

        message += "<h1>Controller name is: #{params[:controller]}</h1>"
        message += "<h1>Action name is: #{params[:action]}</h1>"

        render html: message.html_safe
    end

    def passDataToViews
        @message = "<h1>Hello World From Rails 8, Yoshi Cooremans!</h1>"
        @message += "<h2>Hello World From Rails 8, Yoshi Cooremans!</h2>"
        @message += "<h3>Hello World From Rails 8, Yoshi Cooremans!</h3>"
        @message += "<h4>Hello World From Rails 8, Yoshi Cooremans!</h4>"
        @message += "<h5>Hello World From Rails 8, Yoshi Cooremans!</h5>"
        @message += "<h6>Hello World From Rails 8, Yoshi Cooremans!</h6>"
    end

    def showDateTimeInfo
        @currenttime = DateTime.now
    end

    def conditionalRendering
        @data =  {
            name: "Yoshi Cooremans",
            age: 20,
            isVisible: true,
            loggedIn: false,
            countryCode: "BE",
            workExperience: 2,
            stateCode: nil

        }
    end

    def loopThroughArrays
        @Products = []
        console
        @Products.push({ productId: 1, productName: "Product 1", quantity: 100, unitsInStock: 50, disContinued: false, cost: 3000 })
        @Products.push({ productId: 2, productName: "Product 2", quantity: 200, unitsInStock: 100, disContinued: true, cost: 4000 })
        @Products.push({ productId: 3, productName: "Product 3", quantity: 300, unitsInStock: 150, disContinued: false, cost: 5000 })
        @Products.push({ productId: 4, productName: "Product 4", quantity: 400, unitsInStock: 200, disContinued: true, cost: 6000 })
        @Products.push({ productId: 5, productName: "Product 5", quantity: 500, unitsInStock: 250, disContinued: false, cost: 7000 })
    end

    def LoadUsers
        base_url = "https://fakestoreapi.com/users"
        @users = CallRestAPI(base_url)
    end

    def CallRestAPI(base_url)
        response = HTTParty.get(base_url)
        response.success? ? response.parsed_response : []
    end

    def LoadUsers2
        base_url = "https://fakestoreapi.com/users"
        @image = "https://i.pravatar.cc"
        @users = CallRestAPI(base_url)
    end

    def ShowUserDetails
      redirect_to LoadUserDetails_path(1)
    end

    def LoadUsersDetails
        id = params[:id].to_i

        if id <1 || id > 10
          redirect_to LoadUserDetails_path(1)
          return
        end

        response = HTTParty.get("https://fakestoreapi.com/users/#{id}")
        if response.success?
            @user = response.parsed_response
        else
            @user = nil
        end
    end
end

exercises/ex_basicsofrails/app/controllers/shoppingcart_controller.rb
class ShoppingcartController < ApplicationController
  def index
    @categories = get_response("https://fakestoreapi.com/products/categories").prepend("All Categories")
    @products = get_response("https://fakestoreapi.com/products")
  end

  def product_list
    category_name = params[:category]
    if category_name == "All Categories"
      url = "https://fakestoreapi.com/products"
    else
      url = "https://fakestoreapi.com/products/category/#{category_name.gsub(' ', '%20')}"
    end
    @products = get_response(url)
  end

  def add_cart
    @product= get_response("https://fakestoreapi.com/products/#{params[:product_id]}")
  end

  def remove_cart
  end

  private
  def get_response(url)
    response = HTTParty.get(url)
    response.success? ? response : []
  end
end

exercises/ex_basicsofrails/app/helpers/shoppingcart_helper.rb
module ShoppingcartHelper
end

exercises/ex_basicsofrails/app/views/shoppingcart/_cart.html.erb
<% if product %>
  	<tr class="product-<%= product['id'] %>">
    <input type="hidden" class="product-price" value="<%= product["price"] %>">

    <td><%= product['title'] %></td>
		<td>
			<%= image_tag product["image"], height: '50', width: '50' %>
		</td>
		<td>
			<%= product["price"] %>
		</td>
        <td>
			<div class="d-flex mb-4">
				<button class="btn btn-danger btn-minus px-2 me-2">
					<i class="">-</i>
				</button>

				<div class="form-outline">
					<input min="1" name="quantity" value="1" type="number" class="qty" />
				</div>

				<button class="btn btn-danger btn-plus px-2 ms-2">
					+
				</button>
			</div>
		</td>
        <td>
			<%= link_to remove_cart_path(product['id']), class: "btn btn-danger", remote: true do %>
                <span class="bi bi-trash-fill"></span>
			<% end %>
		</td>
	</tr>
<% end %>

exercises/ex_basicsofrails/app/views/shoppingcart/_product.html.erb
<% @products.each_with_index do |product, index| %>
    <div style="width: 200px;" class="card m-2 p-2 <%= (index%2==0) ? 'evenRow-style' : 'oddRow-style' %>">

        <%= image_tag product["image"], height: '150', class: 'card-img-top' %>

        <div class="card-header" style="height:180px;">
            <p><%= product["title"] %></p>
        </div>


        <div class="card-body">
            <dl>
                <dt>Price</dt>
                <dd><%= product["price"] %></dd>
                <dt>Rating</dt>
                <dd><span class="bi bi-star-fill text-success"></span> <%= product["rating"]["rate"] %> [<%= product["rating"]["count"] %>] </dd>
            </dl>
        </div>

        <div class="card-footer">	
            <%= link_to add_cart_path(product['id']), class: 'btn btn-danger w-100', remote: true do %>		
                        <span class="bi bi-cart4"></span>
                        Add to Shopping Cart	
            <% end %>		
        </div>
    </div>
<% end %>

exercises/ex_basicsofrails/app/views/shoppingcart/add_cart.js.erb
$('.cart-table').append("<%= j render partial: 'cart', locals: { product: @product } %>" );
var count = $('.cart-table tr').length;
$('.cart_count').text(count);
addQtyBtn();
minusQtyBtn();
qtyTextbox();
updateTotalPrice();

exercises/ex_basicsofrails/app/views/shoppingcart/index.html.erb
<div class="container-fluid">
    <header class="bg-danger text-white text-center p-2">
       <h2><span class="bi bi-cart"></span>Shopping Cart Yoshi Cooremans</h2>
    </header>
     <div class="row mt-2">
        <div class="col-md-2">
            <div>
                <label class="form-label">Select a Category</label>
                <div>
                    <%= select_tag(:category, options_for_select(@categories), class: 'form-select category-dropdown') %>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="d-flex flex-wrap overflow-auto product-list" style="height: 550px;">
                <%= render partial: 'product' %>
            </div>
        </div>
        <div class="col-md-4">
            <div>
                <button class="btn btn-danger w-100">
                    <span class="bi bi-cart2"></span>
                    [<span class="cart_count"></span>] Your Shopping Cart Items
                </button>
            </div>
             <div class="mt-2">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Preview</th>
                            <th>Price</th>
                            <th>Qty</th>
                        </tr>
                    </thead>
                    <tbody class="cart-table">
                      
                    </tbody>
                </table>
            </div>
             <div>
                <button class="btn btn-danger w-100">
                    Total:
                    <span class="total_count">0</span> 
                </button>
            </div>
        </div>
    </div>
</div>

exercises/ex_basicsofrails/app/views/shoppingcart/product_list.js.erb
$('.product-list').empty().append("<%= j render partial: 'product' %>");

exercises/ex_basicsofrails/app/views/shoppingcart/remove_cart.js.erb
$(".product-<%= params['cart_id'] %>").remove();
var count = $('.cart-table tr').length;
$('.cart_count').text(count);
updateTotalPrice();